version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
    command: npm run dev
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    command: npm run dev
  latex:
    build:
      context: ./latex
      dockerfile: Dockerfile
    volumes:
      - ../repos:/workdir
    command: tail -f /dev/null
